#!/bin/bash

###################################################################################
# UCK - Ubuntu Customization Kit                                                  #
# Copyright (C) 2006  UCK Team                                                    #
#                                                                                 #
# This program is free software; you can redistribute it and/or                   #
# modify it under the terms of the GNU General Public License                     #
# as published by the Free Software Foundation; version 2                         #
# of the License.                                                                 #
#                                                                                 #
# This program is distributed in the hope that it will be useful,                 #
# but WITHOUT ANY WARRANTY; without even the implied warranty of                  #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                   #
# GNU General Public License for more details.                                    #
#                                                                                 #
# You should have received a copy of the GNU General Public License               #
# along with this program; if not, write to the Free Software                     #
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA. #
###################################################################################

ISO_IMAGE="$1"
CUSTOMIZE_DIR="$2"
REMASTER_HOME=~/tmp

if [ -e libraries/remaster-live-cd.sh ]; then
	SCRIPTS_DIR=`dirname "$0"`
	LIBRARIES_DIR=$SCRIPTS_DIR/libraries
else
	SCRIPTS_DIR=/usr/bin
	LIBRARIES_DIR=/usr/lib/uck/
fi

$LIBRARIES_DIR/remaster-live-cd.sh

echo "Starting CD remastering on " `date`
echo "Customization dir=$CUSTOMIZE_DIR"

if [ -z "$ISO_IMAGE" ]; then
	usage
	exit 1
fi

if [ -z "$CUSTOMIZE_DIR" ]; then
	usage
	exit 1
fi

CUSTOMIZE_ROOTFS="no"
CUSTOMIZE_INITRD="no"
CUSTOMIZE_ISO="no"
KEEP_PREVIOUS_ISO_EXTRACTION="no"
KEEP_PREVIOUS_REMASTER_DIR="no"

if [ -e "$CUSTOMIZE_DIR/customize" ]; then
	CUSTOMIZE_ROOTFS="yes"
fi

if [ -e "$CUSTOMIZE_DIR/customize_initrd" ]; then
	CUSTOMIZE_INITRD="yes"
fi

if [ -e "$CUSTOMIZE_DIR/customize_iso" ]; then
	CUSTOMIZE_ISO="yes"
fi

if [ -e "$CUSTOMIZE_DIR/keep_iso_extraction" ] ; then
	KEEP_PREVIOUS_ISO_EXTRACTION="yes"
fi

if [ "$KEEP_PREVIOUS_ISO_EXTRACTION" = "no" ] || [ ! -e "$ISO_REMASTER_DIR" ] ; then
	$SCRIPTS_DIR/uck-remaster-unpack-iso "$ISO_IMAGE" "$REMASTER_HOME"
fi

if [ "$CUSTOMIZE_ROOTFS" = "yes" ] ; then
	if [ -e "$CUSTOMIZE_DIR/keep_rootfs_extraction" ] ; then
		KEEP_PREVIOUS_REMASTER_DIR="yes"
	fi

	if [ "$KEEP_PREVIOUS_REMASTER_DIR" = "no" ] || [ ! -e "$REMASTER_DIR" ] ; then
		$SCRIPTS_DIR/uck-remaster-unpack-rootfs "$REMASTER_HOME"
	fi
fi

if [ "$CUSTOMIZE_INITRD" = "yes" ] ; then
	$SCRIPTS_DIR/uck-remaster-unpack-initrd "$REMASTER_HOME"
	customize_initrd
fi

if [ "$CUSTOMIZE_ROOTFS" = "yes" ] ; then
	$SCRIPTS_DIR/uck-remaster-chroot-rootfs COSAAAA "$REMASTER_HOME"
	RESULT=$?
	if [ "$RESULT" -ne 0 ]; then
		failure "Running customization script failed, error=$RESULT"
	fi
fi

#if [ "$CUSTOMIZE_ISO" = "yes" ] ; then
#	customize_iso
#fi

if [ "$MANUAL_CUSTOMIZATION_PAUSE" = "yes" ] ; then
	echo "Pausing for manual customization, press Enter when finished..."
	read DUMMY
fi

if [ "$CUSTOMIZE_INITRD" = "yes" ] ; then
	$SCRIPTS_DIR/uck-remaster-pack-initrd "$REMASTER_HOME"
fi

if [ "$CUSTOMIZE_ROOTFS" = "yes" ] ; then
	$SCRIPTS_DIR/uck-remaster-pack-rootfs "$REMASTER_HOME"
fi


remove_remaster_initrd
export -n INITRD_REMASTER_DIR

$SCRIPTS_DIR/uck-remaster-pack-iso "$REMASTER_HOME"

if [ "$CUSTOMIZE_ROOTFS" = "yes" ] ; then
	if [ "$KEEP_PREVIOUS_REMASTER_DIR" = "no" ] ; then
		remove_remaster_dir
	fi
	export -n REMASTER_DIR
fi

if [ "$KEEP_PREVIOUS_ISO_EXTRACTION" = "no" ] ; then
	remove_iso_remaster_dir
fi

echo "Generation completed SUCCESSFULLY, find your ISO in $NEW_FILES_DIR"

exit 0